export * from "./diocese/createDiocese.dto"
export * from "./diocese/updateDiocese.dto"
export * from './role/create.role';
export * from './role/update.role';
export * from "./phone/phone.create";
export * from "./socialmedia/socialmedia.create";
export * from "./phone/phone.create";
export * from "./socialmedia/socialmedia.create";
export * from "./worker/create.worker";
export * from "./user/login";
export * from "./phone/phone.create"
export * from "./socialmedia/socialmedia.create"
export * from "./worker/create.worker"
export * from "./parish/createParish.dto"
export * from "./parish/updateParish.dto";
export * from "./user/login";
export * from "./parish/updateParish.dto";
export * from "./person/create.person";
export * from "./socialmedia/socialmedia.create";
export * from "./degree/create.degree";
export * from "./seminarian/create.seminarian";
export * from "./user/create.user";
export * from "./seminarian/create.Foreing.seminarian";
export * from "./user/update.user";
export * from "./seminarian/update.seminarian";
export * from "./seminarian/get.seminarian";