export * from "./diocese.datasource";
export * from "./role.datasource";
export * from "./stage.datasource"
export * from "./parish.datasource";
export * from "./worker.datasource"
export * from "./instructorPosition.datasource"
export * from "./instructor.datasource";
export * from "./course.datasorce";
export * from "./professor.datasource";
export * from "./user.datasource"
export * from "./subject.datasource";
export * from "./seminarian.datasource";
export * from "./academic.term.datasource";
export * from "./instructuion.datasource";
export * from "./enrollment.dataSource";
export * from "./test.datasource";
export * from "./testScore.datasource";
export * from "./bitacora.datasource";
