export * from "./diocese.datasource";
export * from "./role.datasource";
export * from "./stage.datasource"
export * from "./parish.datasource";
export * from "./worker.datasource"
export * from "./instructorPosition.datasource"
export * from "./instructor.datasource";
export * from "./course.datasorce"
export * from "./professor.datasource"