export * from "./diocese.repository";
export * from "./role.repository";
export * from "./stage.repository";
export * from "./parish.repository"
export * from "./worker.repository";
export * from "./instructorPosition.repository";
export * from "./instructor.repostory";
export * from "./course.repository";
export * from "./professor.repository";
export * from "./user.repository";
export * from "./user.repository"
export * from "./seminarian.repository";
export * from "./subject.repository";
export * from "./academic.tern.repository";
export * from "./instruction.repository";
export * from "./enrollment.repository";
export * from "./test.repository";
export * from "./testScore.repository";
export * from "./bitacora.repository";