export * from "./diocese.entity";
export * from "./permission.entity";
export * from "./role.entity";
export * from "./stage.entity";
export * from "./person.entity";
export * from "./worker.entity";
export * from "./phone.entity";
export * from "./social.media.entity";
export * from "./instructorPosition.entity"
export * from "./instructor.entity"