export * from "./diocese.entity";
export * from "./permission.entity";
export * from "./role.entity";
export * from "./stage.entity";
export * from "./person.entity";
export * from "./worker.entity"
export * from "./parish.entity";
export * from "./phone.entity";
export * from "./social.media.entity";
export * from "./social.media.cate.entity";
export * from "./user.entity";
export * from "./user_entity";
export * from "./degree.entity";
export * from "./foreingseminarian.entity";
export * from "./person.entity";
export * from "./seminarian.entity";