export * from "./diocese";
export * from "./role";
export * from "./stage";
export * from "./user"
export * from "./parish"
export * from "./user"
export * from "./seminarian"
export * from "./worker";
export * from "./instructor";
export * from "./course";
export * from "./professor";
export * from "./user";
export * from "./subject";
export * from "./academicterm";
export * from "./instruction";
export * from "./enrollment";
export * from "./test";
export * from "./testScore";
export * from "./bitacora";